# Generated by Django 5.1.4 on 2025-01-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_usuarioscadastrados_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioscadastrados',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
